export const LOGGED_IN = "LOGGED_IN";
export const LOGOUT = "LOGOUT";
export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const LOGGED_OUT = "LOGGED_OUT";
export const FAILED_LOGIN = "FAILED_LOGIN";
export const FAILED_SIGNUP = "FAILED_SIGNUP";

export const FETCH_RECIPES_PLUS_INGREDIENTS = "FETCH_RECIPES";
export const FETCH_RECIPE_SHOW_PLUS_INGREDIENTS =
  "FETCH_RECIPE_SHOW_PLUS_INGREDIENTS";
export const FETCH_TO_CREATE_RECIPE = "FETCH_TO_CREATE_RECIPE";
export const FETCH_TO_UPDATE_RECIPE = "FETCH_TO_UPDATE_RECIPE";
export const FETCH_TO_DELETE_RECIPE = "FETCH_TO_DELETE_RECIPE";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";

export const FETCH_TO_ADD_INGREDIENT = "FETCH_TO_ADD_INGREDIENT";
export const FETCH_TO_UPDATE_INGREDIENT = "FETCH_TO_UPDATE_INGREDIENt";
export const FETCH_TO_DELETE_INGREDIENT = "FETCH_TO_DELETE_INGREDIENT";